# Gush configuration file, any comments will be lost.
meta-header: "This file is part of the SkeletonDancer package.\n\n(c) Sebastiaan Stok <s.stok@rollerscapes.net>\n\nThis source file is subject to the MIT license that is bundled\nwith this source code in the file LICENSE."
repo_adapter: github
issue_tracker: github
repo_org: rollerworks
repo_name: SkeletonDancer
issue_project_org: rollerworks
issue_project_name: SkeletonDancer
